### ISSUE TITLE
RasPlex autoboots after first reboot

### ISSUE THREAD

**Issue by Drugantibus** [LaurentMarchelli/recalbox-rasplex#12]
After NOOBS finishes installing the OSes I am shown the boot selection screen, where I choose to boot RecalBox. It works fine, however, after I rebooted (soft reboot from RecalBox), it boots automatically to RasPlex without giving me the choice to select which OS to boot. Holding shift during boot has no effect. Appears to be consistent across multiple installations. 

Compiled on Arch Linux, target is a Raspberry Pi 3

**Comment by LaurentMarchelli** [comment]
Hi Alessandro,

Sure, because It is the way it works with (Plex Black Edition or Aeon Nox 5 skin) : 
* to switch from RasPlex to Recalbox you should use the RasPlex menu option, 
* to switch from Recalbox to RasPlex, just reboot.

From Recalbox, if you do not want to reboot to RasPlex, do not reboot, just call shutdown from Recalbox menu. The next times it will boot on Recalbox, until you choose to reboot.

If you prefer to have the boot menu each time, the better way is to use the standard skin (OpenPHT) and then install the skin you want from Rasplex configuration menu.

Check the readme. 
https://github.com/LaurentMarchelli/recalbox-rasplex/blob/master/README.md

Thanks for you feedback, I hope, it helps.
Best regards

**Comment by Drugantibus** [comment]
I see, I didn't see the last section after the installation instructions. 

Thanks for your time!
